"""Material Design Icons lookup for screen rendering.

``mdi/mdi-paths.json`` (generated by ``scripts/build_mdi_json.py`` from the
Apache-2.0 @mdi/svg package) maps every icon name to its single 24x24-viewBox
SVG path. Loaded lazily on first use — inside the render executor job, so the
~3 MB JSON parse never blocks the event loop — and cached for the process
lifetime.

Unknown icon names return ``None`` (widgets draw a neutral placeholder); they
never raise.
"""

from __future__ import annotations

import json
from pathlib import Path

_MDI_FILE = Path(__file__).parent / "mdi" / "mdi-paths.json"

_paths: dict[str, str] | None = None


def icon_path(name: str | None) -> str | None:
    """Return the 24x24 SVG path data for an ``mdi:`` icon name, or None."""
    global _paths  # noqa: PLW0603 - simple one-shot cache
    if not name:
        return None
    paths = _paths
    if paths is None:
        try:
            paths = json.loads(_MDI_FILE.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            paths = {}
        _paths = paths
    return paths.get(name.removeprefix("mdi:"))
