"""Material Design Icons lookup for screen rendering.

``mdi/mdi-paths.json`` (generated by ``scripts/build_mdi_json.py`` from the
Apache-2.0 @mdi/svg package) maps every icon name to its single 24x24-viewBox
SVG path. Loaded lazily on first use — inside the render executor job, so the
~3 MB JSON parse never blocks the event loop — and cached for the process
lifetime.

Unknown icon names return ``None`` (widgets draw a neutral placeholder); they
never raise.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_MDI_FILE = Path(__file__).parent / "mdi" / "mdi-paths.json"


@lru_cache(maxsize=1)
def _load_paths() -> dict[str, str]:
    try:
        return json.loads(_MDI_FILE.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}


def icon_path(name: str | None) -> str | None:
    """Return the 24x24 SVG path data for an ``mdi:`` icon name, or None."""
    if not name:
        return None
    return _load_paths().get(name.removeprefix("mdi:"))
